version: "2"
services:
  master:
    image: fernandopf/rstudiospark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    ports:
      - "8787"
      - "8080"
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
  worker_ferdos:
    image: fernandopf/rstudiospark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    environment:
      - "constraint:node==ferdos"
  worker_fer:
    image: fernandopf/rstudiospark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    environment:
      - "constraint:node==fer"
  worker_pregel:
    image: fernandopf/rstudiospark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    environment:
      - "constraint:node==pregel"
  worker_erdos:
    image: fernandopf/rstudiospark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    environment:
      - "constraint:node==erdos"
  worker_renyi:
    image: fernandopf/rstudiospark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    environment:
      - "constraint:node==renyi"
networks:
  default:
    external:
      name: redcluster2
